### ISSUE TITLE
Control panel water pump updates

### ISSUE THREAD

**Issue by bencaterine** [ESW-NU/AutoAquaponics-v2.0#118]
We need to update the water pump control panel page as follows:
1. Remove status selectors from the individual grow bed cards.
2. Add a new status selector in its own card (choose between "On", "Off", and "Timer"). This controls both grow beds.
    - When "On or "Off" are selected, the grow bed cards should disappear. They should only appear when status is "Timer".
    - status="Timer" means the hardware will alternate between beds A and B at the intervals declared in the "Pump Time" boxes
3. Remove the "Flow Rate" entry boxes from each grow bed. The hardware is not ready to support this yet so we will stick with just the "Pump Time" entry.

Feel free to take liberties with the exact components/styling used. I already updated the firebase `water-pump` collection to reflect the desired changes. Here is a picture of the old GUI front end:
<img width="417" alt="PNG image" src="https://github.com/ESW-NU/AutoAquaponics-v2.0/assets/72643668/bbe54d6f-ba25-424a-9dff-234b00e34c8f">
You will also need to update the firebase writes accordingly.
The current water pump implementation is in the `control-panel-firebase` branch. Pull that branch to get started.
Thanks!

**Comment by andrechen77** [comment]
![image](https://github.com/ESW-NU/AutoAquaponics-v2.0/assets/101299705/d6d5bcf2-3d1b-4993-84da-a971b2e03baa)
Does this look good?

**Comment by bencaterine** [comment]
Yep looks great!
