### ISSUE TITLE
Add snackbar when logging in

### ISSUE THREAD

**Issue by andrechen77** [ESW-NU/AutoAquaponics-v2.0#119]
https://mui.com/material-ui/react-snackbar/

A successful login should show one of these notifs, an unsuccessful one should show an error.

**Comment by ksharma20** [comment]
Can I Pick this up @andrechen77 ?

**Comment by andrechen77** [comment]
lol sure, go for it.

**Comment by andrechen77** [comment]
Update: This should now use the Toast system added in 2b6340f.
