### ISSUE TITLE
'About' page for brief description on aquaponics system

### ISSUE THREAD

**Issue by LesterTai64** [ESW-NU/AutoAquaponics-v2.0#50]
We need a README tab (within navigation bar) called 'About' page. Describe what the system does, important specifications, and info on our group AutoAquaponics

**Comment by billyen33** [comment]
Aim to finish this by the end of the quarter and add pictures. Specific sections we want in this include:

- History
- Biology
- Plumbing
- Electronics
- Software

Get the section layout and graphics done first, then @billyen33 will help write the actual content. You can find images on our blog. Another alternative to making this a new page is to make this part of the home page, and if the user scrolls down while in home page they can get to this information.

**Comment by bencaterine** [comment]
#74
