### ISSUE TITLE
Control Panel Layout Update

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics-v2.0#51]
I propose that we change the control panel layout so that "Tolerances" is the first tab that shows up, and when one goes to the control panel page, that is the tab that is open by default. Right now when you go onto the page it's just blank until the user clicks on a tab, so it's not very clear.

![image](https://user-images.githubusercontent.com/66648349/201544677-112b2564-5b6d-4a51-b5a6-6b85ee1540ac.png)

**Comment by Qasim-Elhabrush** [comment]
I just created a pull request that addresses these suggestions :) I hope you don't mind the contribution.

**Comment by bencaterine** [comment]
closed by #52
