### ISSUE TITLE
Firebase user authentication

### ISSUE THREAD

**Issue by bencaterine** [ESW-NU/AutoAquaponics-v2.0#55]
Figure out how to use firebase authentication to let users log in.
- We may have to restrict data/graph read access to logged in users (to avoid having our read limits maxed out). Ideally we do not have to resort to this but it's possible.
- We want an admin tier that contains only club members - these should be the only people able to edit the control panel.

**Comment by andrechen77** [comment]
closed by [PR #117](https://github.com/ESW-NU/AutoAquaponics-v2.0/pull/117)
