### ISSUE TITLE
Site crashes when toggling quickly between Dashboard and other navbar navlinks

### ISSUE THREAD

**Issue by Qasim-Elhabrush** [ESW-NU/AutoAquaponics-v2.0#57]
Whenever I quickly toggled multiple times between Dashboard and other navbar links like Control Panel or Video Feed an error occurred and caused the website to go blank, the only way to get back to the site was to refresh the page.  
The error that occurred: _"Uncaught TypeError: Cannot read properties of undefined (reading 'max')" at AreaGraph.jsx:13_
I'm going to look into what's going on with that component and see if I can fix it for you.

**Comment by billyen33** [comment]
Strange, I tried replicating this by clicking between the navbar buttons very quickly and it didn't happen for me. Can you confirm this happens on our deployed website: autoaquaponics.org?

**Comment by Qasim-Elhabrush** [comment]
The deployed website does not seem to have the same bug.
