### ISSUE TITLE
Automatic deployment not working

### ISSUE THREAD

**Issue by NU-UrbanAg** [ESW-NU/AutoAquaponics-v2.0#63]
Updating the deploy branch on the GitHub repo is supposed to automatically build and update the react site hosted on Firebase. However it throws the error below (more detail can be seen in Actions tab in GitHub):

> Run npm ci && npm run build
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @testing-library/react@12.1.5
> npm ERR! Found: react@18.0.0
> npm ERR! node_modules/react
> npm ERR!   react@"^18.0.0" from the root project
> npm ERR!   peer react@">=16.8.0" from @emotion/react@11.9.0
> npm ERR!   node_modules/@emotion/react
> npm ERR!     @emotion/react@"^11.9.0" from the root project
> npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.8.1
> npm ERR!     node_modules/@emotion/styled
> npm ERR!       @emotion/styled@"^11.8.1" from the root project
> npm ERR!       3 more (@mui/material, @mui/styled-engine, @mui/system)
> npm ERR!     3 more (@mui/material, @mui/styled-engine, @mui/system)
> npm ERR!   15 more (@emotion/styled, @mui/base, @mui/icons-material, ...)
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"<18.0.0" from @testing-library/react@12.1.5
> npm ERR! node_modules/@testing-library/react
> npm ERR!   @testing-library/react@"^12.1.5" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   peer react@"<18.0.0" from @testing-library/react@12.1.5
> npm ERR!   node_modules/@testing-library/react
> npm ERR!     @testing-library/react@"^12.1.5" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/runner/.npm/_logs/2022-12-08T0[4](https://github.com/ESW-NU/AutoAquaponics-v2.0/actions/runs/3645422309/jobs/6155555607#step:3:5)_[5](https://github.com/ESW-NU/AutoAquaponics-v2.0/actions/runs/3645422309/jobs/6155555607#step:3:6)9_4[8](https://github.com/ESW-NU/AutoAquaponics-v2.0/actions/runs/3645422309/jobs/6155555607#step:3:9)_30[9](https://github.com/ESW-NU/AutoAquaponics-v2.0/actions/runs/3645422309/jobs/6155555607#step:3:10)Z-debug-0.log
> Error: Process completed with exit code 1.

**Comment by bencaterine** [comment]
Seems like github is attempting to run this workflow in all branches, not just deploy. When I opened pull request into main it attempted to run it as well

**Comment by bencaterine** [comment]
Automatic deployment should not be happening on PRs, only on changes to deployment branch.
Turned off for now so we can deploy manually.

**Comment by andrechen77** [comment]
Fixed by 7e9a3a2aedf868af7f5c220fe0ddfb5511a45d46 and 1b1122251a63c43a27229d9715d36ac1ebffa81a
