### ISSUE TITLE
Labels for Y axis cut off if the number is >2 digits long

### ISSUE THREAD

**Issue by NU-UrbanAg** [ESW-NU/AutoAquaponics-v2.0#64]
See TDS graph's Y label, it gets cut off because it's greater than 2 digits long. Need to fix it so it accommodates at least 4 digits.
![image](https://user-images.githubusercontent.com/66647812/206361106-17d7da99-26c7-4d59-b603-5c31c9ff6af5.png)

**Comment by bencaterine** [comment]
closed by #76
