### ISSUE TITLE
Set up Google Analytics Monitoring For Our Website

### ISSUE THREAD

**Issue by NU-UrbanAg** [ESW-NU/AutoAquaponics-v2.0#66]
Set up Google Analytics (or equivalent) with our hosted React site so we can see the following data:
- How many people have gone on which one of our pages and for how long
- Who's been on our Dashboard, which one of our pages are highest traffic

Resources (keep adding useful links to this document): https://docs.google.com/document/d/19ghoqJX2bo0M3_TQEgafKXKwhToJYEdjgfhLxBT42-I/edit

**Comment by bencaterine** [comment]
closed by #79
