### ISSUE TITLE
Security issue with Firebase access

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics-v2.0#67]
Fix these issues so only authenticated users can read and write to our database
![image](https://user-images.githubusercontent.com/66648349/206362159-eb5968be-d67e-467f-b887-e5ce4999daca.png)

**Comment by bencaterine** [comment]
Will work on this

**Comment by bencaterine** [comment]
Fixed by changing firebase rules:
<img width="756" alt="Screen Shot 2023-01-22 at 2 11 45 PM" src="https://user-images.githubusercontent.com/72643668/213937998-c5115126-5a95-402e-afd3-751645caad62.png">
Should no longer receive "insecure" emails.
