### ISSUE TITLE
Fix home page bug in Safari

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics-v2.0#69]
The Homepage looks messed up on Safari with images being vertical stretched in the cards and the main system image too far to the left. This is likely related to/can be fixed by responsive design as it looks like this on mobile too.

![image](https://user-images.githubusercontent.com/66648349/206595763-c6494a74-ec49-4ea2-af1d-c62023b6db9b.png)
![image](https://user-images.githubusercontent.com/66648349/206595771-76207b9a-3c94-4976-ae96-40dbf4a303ac.png)
![image](https://user-images.githubusercontent.com/66648349/206595781-07aebfa6-c8cd-4764-88e3-eb98ad423fa2.png)

**Comment by Kd-Here** [comment]
Hey @billyen33 can I work on it.
I had basic understanding of frontend created and solved such issues for static page.
But it will first time with React would you please guide if I need help

**Comment by billyen33** [comment]
@Kd-Here Of course, thank you for your contribution! Let us know how it goes!

**Comment by bencaterine** [comment]
closed by #84
