### ISSUE TITLE
Make nav bar responsive and collapsible on mobile

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics-v2.0#71]
Follow this guide to make the nav bar responsive so that it collapses on mobile display: https://blog.logrocket.com/create-responsive-navbar-react-css/

**Comment by kemps-medeiros** [comment]
Hi @billyen33 , Can I try to do this task?

**Comment by kemps-medeiros** [comment]
@billyen33 
I created this PR to solve this issue. As soon as you can check, and if you need any modifications, please let me know. Thanks!

https://github.com/ESW-NU/AutoAquaponics-v2.0/pull/72

**Comment by bencaterine** [comment]
See navbar-responsive branch

**Comment by billyen33** [comment]
Hey @kemps-medeiros, love to get your help! I think the framework of what you laid down looks great. I have a few suggestions for what might make it look better:
1. The menu can use a smoother transition when it collapses, I think right now it seems a bit abrupt especially on desktop since it goes from a long list of items to a very small icon on the right. We're trying to find a cool animation for this, so if you have ideas that would be very welcomed :)
2. This might be more of a matter of rearranging things on the nav bar, but the items to the left of the Login button merges and end up on the right of the Login button, which seems a bit bizarre.
3. The menu that opens from clicking on the collapsed icon opens on the left of the screen but the icon is on the right. I think logically it should open on the right to match the UI.

@bencaterine Feel free to add to this

Obrigado!

**Comment by bencaterine** [comment]
closed by #86
